/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_database;

/**
 *
 * @author icc.caloocan
 */

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;


public class MAIN_FORM extends javax.swing.JFrame {
    Connection c;
    PreparedStatement st;
    ResultSet r;
   
    public MAIN_FORM() {
        initComponents();
        c = JAVA_DATABASE.connect();
         loadTable();
    }

    public void loadTable(){
        try {
            String sql = " select * from INFO";
            st = c.prepareStatement(sql);
            r = st.executeQuery();
            tableta.setModel(DbUtils.resultSetToTableModel(r));
                
        }catch (Exception e)
        {
            
        }
    } 
    public void clear()
    {
        
        txt1.setText("");
        txt2.setText("");
        txt3.setText("");
        txt4.setText("");
    
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        hanap = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        DELETE = new javax.swing.JButton();
        ADD1 = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableta = new javax.swing.JTable();
        hanap1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 2, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Markme");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 660, 640, 70);

        hanap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hanapActionPerformed(evt);
            }
        });
        getContentPane().add(hanap);
        hanap.setBounds(610, 30, 390, 40);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Age :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 360, 100, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Search :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(510, 30, 100, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("ID :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 150, 100, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("First Name :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 220, 140, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Last Name :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 290, 140, 40);
        jPanel1.add(txt3);
        txt3.setBounds(150, 360, 260, 40);

        txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt4ActionPerformed(evt);
            }
        });
        jPanel1.add(txt4);
        txt4.setBounds(150, 150, 260, 40);

        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        jPanel1.add(txt1);
        txt1.setBounds(150, 220, 260, 40);
        jPanel1.add(txt2);
        txt2.setBounds(150, 290, 260, 40);

        DELETE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DELETE.setText("DELETE");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        jPanel1.add(DELETE);
        DELETE.setBounds(1000, 590, 160, 50);

        ADD1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ADD1.setText("ADD");
        ADD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD1ActionPerformed(evt);
            }
        });
        jPanel1.add(ADD1);
        ADD1.setBounds(430, 590, 160, 50);

        Update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Update.setText("UPDATE");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update);
        Update.setBounds(710, 590, 160, 50);

        tableta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Age"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabletaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableta);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(430, 100, 730, 460);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 800);
        getContentPane().add(hanap1);
        hanap1.setBounds(610, 30, 390, 40);

        setSize(new java.awt.Dimension(1218, 834));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed

 try {
          String val1 = txt1.getText();
          String val2 = txt2.getText();
          String val3 = txt3.getText();
          String val4 = txt4.getText();
          String sql = "update INFO set FirstName='"+ val1+ "',LastName='" +val2+ "',AGE='"+val3+ "' where ID='" + val4+ "'";

          st = c.prepareStatement(sql);
          st.execute();
          loadTable();
          r.close();
          st.close();
 } catch(Exception e)
       {
        JOptionPane.showMessageDialog(null, e);
       }




        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        try{
            int i = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete this? ","Delete",JOptionPane.YES_NO_OPTION);
            if (i==0){
                String sql = "delete from INFO where ID=?";
                st = c.prepareStatement(sql);
                st.setString(1, txt4.getText());
                st.execute();
              loadTable();
            r.close();
            st.close();      
            }else{
                
              
            }
            
        
        }catch(Exception e){
         JOptionPane.showMessageDialog(null, e);       
        }















        // TODO add your handling code here:
    }//GEN-LAST:event_DELETEActionPerformed

    private void tabletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabletaMouseClicked
        DefaultTableModel Mark = (DefaultTableModel)tableta.getModel();
        int selectedRowIndex = tableta.getSelectedRow();
       
        txt1.setText(Mark.getValueAt(selectedRowIndex, 1).toString());
        txt2.setText(Mark.getValueAt(selectedRowIndex, 2).toString());
        txt3.setText(Mark.getValueAt(selectedRowIndex, 3).toString());
        txt4.setText(Mark.getValueAt(selectedRowIndex, 0).toString());
        




        // TODO add your handling code here:
    }//GEN-LAST:event_tabletaMouseClicked

    private void hanapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hanapActionPerformed
        // TODO add your handling code here:
          DefaultTableModel Mark = (DefaultTableModel)tableta.getModel();
          String search_data = hanap.getText().toLowerCase();
          TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(Mark);
          tableta.setRowSorter(tr);
          tr.setRowFilter(RowFilter.regexFilter(search_data));
    }//GEN-LAST:event_hanapActionPerformed

    private void txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt4ActionPerformed

    private void ADD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD1ActionPerformed
    try {
           String sql = "insert into INFO(FirstName, LastName , Age ) values (?, ?, ?)";
           st = c.prepareStatement(sql);
           st.setString(1, txt1.getText());
           st.setString(2, txt2.getText());
           st.setString(3, txt3.getText());
           st.execute();
           clear();
           loadTable();
           r.close();
           st.close();
           
       } catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }        // TODO add your handling code here:
    }//GEN-LAST:event_ADD1ActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAIN_FORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD1;
    private javax.swing.JButton DELETE;
    private javax.swing.JButton Update;
    private javax.swing.JTextField hanap;
    private javax.swing.JTextField hanap1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableta;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    // End of variables declaration//GEN-END:variables
}
