/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee111819;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author icc.caloocan
 */
public class ADDALLOW extends javax.swing.JFrame {
     Connection con=null;
    PreparedStatement pst =null;
     ResultSet rs =null;
    /**
     * Creates new form ADDALLOW
     */
    public ADDALLOW() {
        initComponents();
        con=Employee111819.connect();
          loadTable();
        
    }
    
        public void loadTable(){
        try {
            String sql = "select * from ALLOWANCE";
            pst = con.prepareStatement(sql);
            rs= pst.executeQuery();
            tableta.setModel(DbUtils.resultSetToTableModel(rs));
                
        }catch (Exception e)
        {
            
        }
    }
    public void clear(){
        hanap.setText("");
        id.setText("");
        ln.setText("");
          buttonGroup1.clearSelection();
        department.setText("");
        job.setText("");
        salary.setText("");
        o.setText("");
        med.setText("");
        
        trans.setText("");
        food.setText("");
        ot.setText("");
        rph.setText("");
        total.setText("");
    }
    String gender="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        hanap = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ln = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        job = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        o = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        med = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        trans = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ot = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        rph = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        department = new javax.swing.JTextField();
        food = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel1.setText("Employee First Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 280, 160, 32);
        getContentPane().add(fn);
        fn.setBounds(40, 320, 260, 40);

        hanap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hanapActionPerformed(evt);
            }
        });
        hanap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hanapKeyReleased(evt);
            }
        });
        getContentPane().add(hanap);
        hanap.setBounds(170, 40, 690, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("GENDER");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 470, 217, 33);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel3.setText("Employee ID ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 40, 110, 32);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 30, 830, 60);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setText("ADD ALLOWANCE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 110, 390, 60);

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id);
        id.setBounds(40, 230, 260, 40);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel5.setText("Employee Last Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 370, 160, 32);
        getContentPane().add(ln);
        ln.setBounds(40, 410, 260, 40);

        buttonGroup1.add(male);
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        getContentPane().add(male);
        male.setBounds(40, 510, 70, 23);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel7.setText("Salary");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 750, 160, 32);
        getContentPane().add(salary);
        salary.setBounds(40, 790, 190, 40);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel8.setText("JOB Title");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 660, 110, 32);
        getContentPane().add(job);
        job.setBounds(40, 700, 190, 40);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel9.setText("Employee ID ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 190, 110, 32);
        getContentPane().add(o);
        o.setBounds(440, 280, 190, 40);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel10.setText("Overtime");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(440, 240, 110, 32);
        getContentPane().add(med);
        med.setBounds(440, 370, 190, 40);

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel11.setText("Medical");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(440, 330, 110, 32);
        getContentPane().add(trans);
        trans.setBounds(440, 460, 190, 40);

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel12.setText("Transpo Allowance");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(440, 420, 140, 32);

        ot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otActionPerformed(evt);
            }
        });
        getContentPane().add(ot);
        ot.setBounds(740, 270, 190, 40);

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee111819/1.png"))); // NOI18N
        jButton6.setText("       BACK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(860, 110, 180, 60);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel13.setText("Total Overtime");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(740, 230, 110, 32);
        getContentPane().add(rph);
        rph.setBounds(740, 360, 190, 40);

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel14.setText("Rate Per Hour");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(740, 320, 110, 32);

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        getContentPane().add(total);
        total.setBounds(740, 480, 90, 40);

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel15.setText("Total Allowance");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(740, 430, 140, 32);

        jButton2.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(840, 540, 90, 40);

        jButton4.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jButton4.setText("Calculate");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(840, 480, 90, 40);

        jButton5.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jButton5.setText("Save");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(740, 540, 90, 40);

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel17.setText("Department");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(40, 570, 110, 32);
        getContentPane().add(department);
        department.setBounds(40, 610, 190, 40);

        food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodActionPerformed(evt);
            }
        });
        getContentPane().add(food);
        food.setBounds(440, 550, 190, 40);

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel18.setText("Food Allowance");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(440, 510, 140, 32);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel4.setText("COMPUTATION");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(355, Short.MAX_VALUE))
        );

        buttonGroup1.add(female);
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        tableta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "EmpID", "FirstName", "LastName", "Gender", "Department", "JobTitle", "Salary", "OverTime", "Medical", "TranspoAllowance", "FoodAllowance", "TotalOverTime", "RatePerDay", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabletaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableta);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(female, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(female))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 190, 1030, 670);

        setSize(new java.awt.Dimension(1088, 941));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        MAIN obj = new MAIN();
        obj.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void hanapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hanapActionPerformed
  



  // TODO add your handling code here:
    }//GEN-LAST:event_hanapActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  try{
            int i = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete this? ","Delete",JOptionPane.YES_NO_OPTION);
            if (i==0){
                String sql = "delete from ALLOWANCE where EmpID=?";
                pst = con.prepareStatement(sql);
                pst.setString(1, id.getText());
                pst.execute();
              loadTable();
            rs.close();
            pst.close();      
            }else{
      
            }
            
        
        }catch(Exception e){
         JOptionPane.showMessageDialog(null, e);       
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
double eight = 8;
double days = 25;
double rpd = 0;
double overtimerate=1.5;
int basicsalary = Integer.parseInt(salary.getText());
int overtime =Integer.parseInt(o.getText());
double total_overtime=overtime*overtimerate;
String tat = String.valueOf(total_overtime);
ot.setText(tat);
String t = String.valueOf(total_overtime);
rpd=basicsalary/days/eight;
rph.setText(t);

int medical = Integer.parseInt(med.getText());
int bonus =Integer.parseInt(trans.getText());
int other = Integer.parseInt(food.getText());
int total1 = medical+bonus+other;
double grandtotal = total_overtime*rpd+total1;
String total2 = String.valueOf(grandtotal);
total.setText(total2);
        



    }//GEN-LAST:event_jButton4ActionPerformed

    private void otActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try {
           String sql = "insert into ALLOWANCE(EmpID,FirstName,LastName,Gender,Department,JobTitle,Salary,OverTime,Medical,TranspoAllowance,FoodAllowance,TotalOverTime,RatePerDay,Total) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
           pst = con.prepareStatement(sql);
           pst.setString(1, id.getText());           
           pst.setString(2, fn.getText());
           pst.setString(3, ln.getText());
           pst.setString(4, gender);
           pst.setString(5, department.getText());
           pst.setString(6, job.getText());
           pst.setString(7, salary.getText());
           pst.setString(8, o.getText());
           pst.setString(9, med.getText());
           pst.setString(10, trans.getText());
           pst.setString(11, food.getText());
           pst.setString(12, ot.getText());
           pst.setString(13, rph.getText());
           pst.setString(14, total.getText());
           pst.execute(); 
        
           loadTable();
              rs.close();
           pst.close();
           clear();
           
         
           
       } catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
gender="Male";        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void foodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodActionPerformed

    private void hanapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hanapKeyReleased
 try {
            String sql = "select * from TBL_USERS where EmpID=?";
            pst=con.prepareStatement(sql);
            pst.setString(1, hanap.getText());
            rs=pst.executeQuery();
            String val = rs.getString("EmpID");
            id.setText(val);
            String val2=rs.getString("FirstName");
            fn.setText(val2);
            String val3=rs.getString("LastName");
            ln.setText(val3);
            String v4 = rs.getString("Gender");
            if(v4.equals("male")) {
                male.setSelected(true);
            }
            else {
                female.setSelected(true);
            }
            String val4=rs.getString("Department");
            department.setText(val4);
            String val5=rs.getString("JobTitle");
            job.setText(val5);
            String val6=rs.getString("Salary");
            salary.setText(val6);

        }catch(Exception e){
            
        }

        finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_hanapKeyReleased

    private void tabletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabletaMouseClicked

        DefaultTableModel Mark = (DefaultTableModel)tableta.getModel();
        int selectedRowIndex = tableta.getSelectedRow();

        id.setText(Mark.getValueAt(selectedRowIndex, 1).toString());
        fn.setText(Mark.getValueAt(selectedRowIndex, 2).toString());
        ln.setText(Mark.getValueAt(selectedRowIndex, 3).toString());
        String gender=Mark.getValueAt(selectedRowIndex,4).toString();
        if(gender.equals("Male")){
            male.setSelected(true);
        }
        else{
            female.setSelected(true);
        }
        department.setText(Mark.getValueAt(selectedRowIndex, 5).toString());
        job.setText(Mark.getValueAt(selectedRowIndex, 6).toString());
        salary.setText(Mark.getValueAt(selectedRowIndex, 7).toString());
        o.setText(Mark.getValueAt(selectedRowIndex, 8).toString());
        med.setText(Mark.getValueAt(selectedRowIndex, 9).toString());
        trans.setText(Mark.getValueAt(selectedRowIndex, 10).toString());
        food.setText(Mark.getValueAt(selectedRowIndex, 11).toString());
        ot.setText(Mark.getValueAt(selectedRowIndex, 12).toString());
        rph.setText(Mark.getValueAt(selectedRowIndex, 13).toString());
        total.setText(Mark.getValueAt(selectedRowIndex, 14).toString());
    }//GEN-LAST:event_tabletaMouseClicked

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        gender="Female";        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADDALLOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADDALLOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADDALLOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADDALLOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADDALLOW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField department;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fn;
    private javax.swing.JTextField food;
    private javax.swing.JTextField hanap;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField job;
    private javax.swing.JTextField ln;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField med;
    private javax.swing.JTextField o;
    private javax.swing.JTextField ot;
    private javax.swing.JTextField rph;
    private javax.swing.JTextField salary;
    private javax.swing.JTable tableta;
    private javax.swing.JTextField total;
    private javax.swing.JTextField trans;
    // End of variables declaration//GEN-END:variables
}
