
package employee111819;

import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class GeneratePayslip extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form GeneratePayslip
     */
    public GeneratePayslip() {
        initComponents();
         con = Employee111819.connect();
         enable();
         clear();
    }
    
  public void enable() {
        id.setEditable(false);
        fn.setEditable(false);
        ln.setEditable(false);
        department.setEditable(false);
        job.setEditable(false);
        salary.setEditable(false);
        hired.setEditable(false);
    }
public void clear() {
        search.setText("");
        id.setText("");
        fn.setText("");
        ln.setText("");
          buttonGroup1.clearSelection();
        department.setText("");
        job.setText("");
        hired.setText("");
        salary.setText("");
        buttonGroup1.clearSelection();
    }
String gender="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ln = new javax.swing.JTextField();
        salary = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        job = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        department = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        hired = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel10.setText("Employee ID ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 210, 110, 32);
        getContentPane().add(id);
        id.setBounds(40, 250, 190, 40);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel4.setText("Employee First Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 300, 160, 32);
        getContentPane().add(fn);
        fn.setBounds(40, 340, 190, 40);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel6.setText("Employee Last Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 390, 160, 32);
        getContentPane().add(ln);
        ln.setBounds(40, 430, 190, 40);

        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });
        getContentPane().add(salary);
        salary.setBounds(400, 430, 190, 40);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel7.setText("Salary");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(400, 390, 160, 32);
        getContentPane().add(job);
        job.setBounds(400, 340, 190, 40);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel5.setText("Job Title");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(400, 300, 160, 32);
        getContentPane().add(department);
        department.setBounds(400, 250, 190, 40);

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel11.setText("Department");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(400, 210, 110, 32);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel9.setText("Gender");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(30, 290, 160, 32);

        hired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiredActionPerformed(evt);
            }
        });
        jPanel3.add(hired);
        hired.setBounds(390, 330, 190, 40);

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel12.setText("Date Hired");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(390, 290, 160, 32);

        buttonGroup1.add(female);
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel3.add(female);
        female.setBounds(130, 350, 93, 23);

        buttonGroup1.add(male);
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel3.add(male);
        male.setBounds(30, 350, 80, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 190, 620, 410);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel8.setText("Salary");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(400, 390, 160, 32);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel2.setText("Employee ID :");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(0, 120, 220, 30);

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel4.add(search);
        search.setBounds(180, 30, 290, 40);

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel16.setText("Employee ID");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(70, 30, 110, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 650, 110);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel13.setText("Department");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(400, 210, 110, 32);

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel14.setText("Department");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(400, 210, 110, 32);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel3.setText("Employee Information :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 120, 220, 30);

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel15.setText("Employee ID");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(70, 30, 110, 40);

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Generate Payslip");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 600, 420, 80);

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee111819/1.png"))); // NOI18N
        jButton6.setText("       BACK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(460, 610, 163, 60);

        jMenu3.setText("File");

        jMenuItem2.setText("Generate");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar2.add(jMenu3);
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        setSize(new java.awt.Dimension(663, 765));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryActionPerformed

    private void hiredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hiredActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
 try {
            String sql = "select * from TBL_USERS where EMPID=?";

            pst =con.prepareStatement(sql);
            pst.setString(1, search.getText());
            rs = pst.executeQuery();

            String val1 = rs.getString("EmpID");
            id.setText(val1);

            String val2 = rs.getString("FirstName");
            fn.setText(val2);

            String val3 = rs.getString("LastName");
            ln.setText(val3);

            String val4 = rs.getString("Gender");
            if(val4.equals("male")) {
                male.setSelected(true);
            }
            else {
                female.setSelected(true);
            }

            String val5 = rs.getString("Hired");
            hired.setText(val5);

            String val6 = rs.getString("Department");
            department.setText(val6);

            String val7 = rs.getString("JobTitle");
            job.setText(val7);

            String val8 = rs.getString("Salary");
            salary.setText(val8);
        }
        catch(Exception exc) {

        }

        finally {
            try {
                rs.close();
                pst.close();
            }
            catch(Exception exc) {
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_searchKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        MAIN obj = new MAIN();
        obj.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
  String val1 = fn.getText();
        String val2 = hired.getText();
        
        JFileChooser dialog = new JFileChooser();
        dialog.setSelectedFile(new File(val1 + " " + val2 + " - Salary Slip" + ".pdf"));
        
        int dialogResult = dialog.showSaveDialog(null);
        if(dialogResult == JFileChooser.APPROVE_OPTION) {
            
            String path = dialog.getSelectedFile().getPath();
            
            try {
                Document myDoc = new Document();
                PdfWriter writer = PdfWriter.getInstance(myDoc, new FileOutputStream(path));
                myDoc.open();
                
                myDoc.add(new Paragraph("PAY SLIP", FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
                myDoc.add(new Paragraph(new java.util.Date().toString()));
                myDoc.add(new Paragraph("---------------------------------------------------------", FontFactory.getFont(FontFactory.TIMES_BOLD,15)));
                
                String val3 = department.getText();
                String val4 = job.getText();
                myDoc.add(new Paragraph("EMPLOYEE DETAILS", FontFactory.getFont(FontFactory.TIMES_BOLD,15)));
                myDoc.add(new Paragraph("Name of Employee: " + val1 + " " + val2, FontFactory.getFont(FontFactory.TIMES_BOLD,15,Font.BOLD)));
                myDoc.add(new Paragraph("Department: " + val3, FontFactory.getFont(FontFactory.TIMES_BOLD,15,Font.BOLD)));
                myDoc.add(new Paragraph("Job Title: " + val4, FontFactory.getFont(FontFactory.TIMES_BOLD,15,Font.BOLD)));
                myDoc.add(new Paragraph("---------------------------------------------------------", FontFactory.getFont(FontFactory.TIMES_BOLD,15,Font.BOLD)));
                
                String val5 = id.getText();
                String val6 = salary.getText();
                
                String sql = "select * from ALLOWANCE where EmpID='" + val5 + "'";
                pst = con.prepareStatement(sql);
                rs=pst.executeQuery();
                String val7 = rs.getString("Overtime");
                String val8 = rs.getString("Medical");
                String val9 = rs.getString("TranspoAllowance");
                String val10 = rs.getString("FoodAllowance");
                String val11 = rs.getString("TotalOverTime");
                String val12 = rs.getString("RatePerDay");
                String val13 = rs.getString("Total");
                
                myDoc.add(new Paragraph("Salary", FontFactory.getFont(FontFactory.TIMES_BOLD,15)));
                myDoc.add(new Paragraph("Basic Salary: " + val6, FontFactory.getFont(FontFactory.TIMES_BOLD,15)));
                myDoc.add(new Paragraph("Overtime: " + val7, FontFactory.getFont(FontFactory.TIMES_BOLD,15)));
                myDoc.add(new Paragraph("Medical: " + val8, FontFactory.getFont(FontFactory.TIMES_BOLD,15)));
                myDoc.add(new Paragraph("Transportation: " + val9, FontFactory.getFont(FontFactory.TIMES_BOLD,15)));
                myDoc.add(new Paragraph("Food Allowance: " + val10, FontFactory.getFont(FontFactory.TIMES_BOLD,15)));
                myDoc.add(new Paragraph("Total Overtime: " + val11, FontFactory.getFont(FontFactory.TIMES_BOLD,15)));
                myDoc.add(new Paragraph("Rate Per Day : " + val12, FontFactory.getFont(FontFactory.TIMES_BOLD,15)));
                myDoc.add(new Paragraph("Total Allowance : " + val13, FontFactory.getFont(FontFactory.TIMES_BOLD,15)));
                
                myDoc.add(new Paragraph("---------------------------------------------------------", FontFactory.getFont(FontFactory.TIMES_BOLD,15)));
                
                String val14 = id.getText();
                       
                String g = "select * from CLICKD where EmpID='" + val14 + "'";
                pst = con.prepareStatement(g);
                rs=pst.executeQuery();
                
                String val15 = rs.getString("SSS");
                String val16 = rs.getString("PagIbig");
                String val17 = rs.getString("PhilHealth");
                String val18 = rs.getString("Others");
                String val19 = rs.getString("Netpay");
                
                 myDoc.add(new Paragraph("Deduction", FontFactory.getFont(FontFactory.TIMES_BOLD,15)));
                myDoc.add(new Paragraph("SSS : "+val15, FontFactory.getFont(FontFactory.TIMES_BOLD,15)));
                myDoc.add(new Paragraph("PagIbig : " + val16, FontFactory.getFont(FontFactory.TIMES_BOLD,15)));
                myDoc.add(new Paragraph("PhilHealth : " + val17, FontFactory.getFont(FontFactory.TIMES_BOLD,15)));
                myDoc.add(new Paragraph("Others : " + val18, FontFactory.getFont(FontFactory.TIMES_BOLD,15)));
                myDoc.add(new Paragraph("NetPay : " + val19, FontFactory.getFont(FontFactory.TIMES_BOLD,15)));
                myDoc.add(new Paragraph("---------------------------------------------------------", FontFactory.getFont(FontFactory.TIMES_BOLD,15)));
                myDoc.newPage();
                myDoc.close();
                JOptionPane.showMessageDialog(null, "Report was successfully generated");
              
               
            }
            
            catch(Exception e) {
                
                JOptionPane.showMessageDialog(null, e);
                
            }
        
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
gender="male";        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
gender="female";           // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneratePayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneratePayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneratePayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneratePayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneratePayslip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField department;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fn;
    private javax.swing.JTextField hired;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField job;
    private javax.swing.JTextField ln;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField salary;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
