package employee111819;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author icc.caloocan
 */
public class MANAGEEMPLOYEE extends javax.swing.JFrame {
     Connection con=null;
    PreparedStatement pst =null;
     ResultSet rs =null;
   
    /**
     * Creates new form MANAGEEMPLOYEE
     */
    public MANAGEEMPLOYEE() {
        initComponents();
       con=Employee111819.connect();

       fillcombo();
      Fillcombo();
      fillCombo();
      loadTable();
      
     loadTable();
      
    }
    public void aw(){

    }
   
        public void clear()
    {
        id.setText("");
        fn.setText("");
        ln.setText("");
        a.setText("");
        buttonGroup1.clearSelection();
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);
        salary.setText("");
        department.setSelectedItem("-Select-");
        status.setSelectedItem("-Select-");
        job.setSelectedItem("-Select-");
    }
  
         String gender= "";
    
       public void loadTable(){
        try {
            String sql = "select * from TBL_USERS";
            pst = con.prepareStatement(sql);
            rs= pst.executeQuery();
            tableta.setModel(DbUtils.resultSetToTableModel(rs));
                
        }catch (Exception e)
        {
            
        }
    }

       
          public void fillcombo(){
             status.addItem("Single");
             status.addItem("Married");
             status.addItem("In Relationship");
             status.addItem("Devorce");
             status.addItem("Widow");
       }
          
           public void Fillcombo(){
             department.addItem("Company");
             department.addItem("Own Business");
             department.addItem("none");
             department.addItem("n/a");
             department.addItem("Office");
       }
       
             public void fillCombo(){
             job.addItem("Other");
                job.addItem("Manager");
             job.addItem("Employee");
             job.addItem("Office");
             job.addItem("Constraction");
       }
             
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ln = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        department = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        job = new javax.swing.JComboBox<>();
        update = new javax.swing.JButton();
        ADD = new javax.swing.JButton();
        ref = new javax.swing.JButton();
        del = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableta = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        status = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        HANAP = new javax.swing.JTextField();
        salary = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SEARCH EMPLOYEE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(770, 50, 150, 40);

        fn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fnKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnKeyTyped(evt);
            }
        });
        getContentPane().add(fn);
        fn.setBounds(40, 190, 240, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GENDER");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(400, 60, 217, 33);

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        getContentPane().add(id);
        id.setBounds(40, 100, 240, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Employee Last Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 250, 217, 33);

        ln.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lnKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lnKeyTyped(evt);
            }
        });
        getContentPane().add(ln);
        ln.setBounds(40, 290, 240, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DATE OF BIRTH");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 450, 217, 33);

        a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aKeyTyped(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(40, 390, 240, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Employee Age");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 350, 217, 33);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DATE OF HIRED");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 540, 217, 33);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Employee ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 60, 217, 33);

        female.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(female);
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        getContentPane().add(female);
        female.setBounds(490, 100, 93, 25);

        male.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(male);
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        getContentPane().add(male);
        male.setBounds(390, 100, 60, 25);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Employee First Name");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 150, 217, 33);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SALARY");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(370, 150, 217, 33);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DEPARTMENT");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(370, 250, 217, 33);

        department.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-" }));
        getContentPane().add(department);
        department.setBounds(370, 290, 230, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("JOB TITLE");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(370, 430, 217, 33);

        job.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        job.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-" }));
        getContentPane().add(job);
        job.setBounds(370, 470, 230, 40);

        update.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(490, 520, 120, 40);

        ADD.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        ADD.setText("ADD");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        getContentPane().add(ADD);
        ADD.setBounds(360, 520, 120, 40);

        ref.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        ref.setText("REFESH");
        ref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refActionPerformed(evt);
            }
        });
        getContentPane().add(ref);
        ref.setBounds(490, 570, 120, 40);

        del.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        del.setText("DELETE");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        getContentPane().add(del);
        del.setBounds(360, 570, 120, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Employee Details");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 11, 217, 33);

        tableta.setBackground(new java.awt.Color(102, 102, 102));
        tableta.setForeground(new java.awt.Color(255, 255, 255));
        tableta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "EmpID", "FIRSTNAME", "LASTNAME", "AGE", "BIRTH", "HIRED", "GENDER", "SALARY", "DEPARTMENT", "STATUS", "Job"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabletaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(660, 110, 730, 530);

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee111819/1.png"))); // NOI18N
        jButton5.setText("       BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(450, 630, 180, 60);

        status.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-" }));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        getContentPane().add(status);
        status.setBounds(370, 380, 230, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("STATUS");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(370, 340, 217, 33);

        HANAP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                HANAPKeyReleased(evt);
            }
        });
        getContentPane().add(HANAP);
        HANAP.setBounds(920, 50, 310, 40);

        salary.setToolTipText("Must be Peso Currency");
        getContentPane().add(salary);
        salary.setBounds(370, 190, 230, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee111819/rapbars.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(710, 50, 50, 40);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(40, 490, 230, 50);
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(40, 580, 230, 50);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(700, 40, 540, 60);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee111819/33.jpg"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 1410, 700);

        setSize(new java.awt.Dimension(1419, 738));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        MAIN obj = new MAIN();
         obj.setVisible(true);
           this.dispose();       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
   try {
           String sql = "insert into TBL_USERS(EmpID,FirstName,LastName,Age,Birthday,Hired,Gender,Salary,Department,Status,JobTitle) values(? ,? ,? ,? ,? ,? ,? ,? ,? ,?,?)";
           pst = con.prepareStatement(sql);
           pst.setString(1, id.getText());           
           pst.setString(2, fn.getText());
           pst.setString(3, ln.getText());
           pst.setString(4, a.getText());
           SimpleDateFormat sdf = new SimpleDateFormat("YYY-MM-DD");
           String dob= sdf.format(jDateChooser1.getDate());
           pst.setString(5,dob);
           
           String dhired = sdf.format(jDateChooser2.getDate());
             pst.setString(6,dhired);
      
           pst.setString(7, gender);
           pst.setString(8, salary.getText());
           pst.setString(9, department.getSelectedItem().toString());
           pst.setString(10, status.getSelectedItem().toString());
           pst.setString(11, job.getSelectedItem().toString());
           pst.execute();
        
           loadTable();
              rs.close();
           pst.close();
           clear();
       update.setEnabled(true);
      del.setEnabled(true);
      ref.setEnabled(true);
         
           
       } catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
  
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed

    gender="male";        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
    gender="female";        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
  try {     
        String v1 = id.getText();
        String v2 = fn.getText();
        String v3 = ln.getText();
        String v4 = a.getText();
       SimpleDateFormat sdf = new SimpleDateFormat("MMM d, yyyy");
        String dob= sdf.format(jDateChooser1.getDate());
        SimpleDateFormat sdf1 = new SimpleDateFormat("MMM d, yyyy");
        String hired= sdf1.format(jDateChooser2.getDate());
        String v5 = gender;
        String v6 = salary.getText();
        String v7 = department.getSelectedItem().toString();
        String v8 = status.getSelectedItem().toString();
        String v9 = job.getSelectedItem().toString();
         String sql = "update TBL_USERS set FirstName='"+v2+"',LastName='"+v3+"',Age='"+v4+"', Birthday='"+dob+"', Hired=' "+hired+ "',Gender='"+v5+"',Salary='"+v6+"',Department='"+v7+"',Status='"+v8+"',Jobtitle='"+v9+"'where EmpID='"+v1+"'";
                  pst =con.prepareStatement(sql);
                  pst.execute();
                  JOptionPane.showMessageDialog(null, "DATA UPDATED");
                  clear();
                  loadTable(); 
        rs.close();
        pst.close();
        } catch (Exception e) {
                 JOptionPane.showMessageDialog(null, e);
        }  
    }//GEN-LAST:event_updateActionPerformed

    private void tabletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabletaMouseClicked
   DefaultTableModel Mark = (DefaultTableModel)tableta.getModel();
        int selectedRowIndex = tableta.getSelectedRow();
        id.setText(Mark.getValueAt(selectedRowIndex, 1).toString());
        fn.setText(Mark.getValueAt(selectedRowIndex, 2).toString());
        ln.setText(Mark.getValueAt(selectedRowIndex, 3).toString());
        a.setText(Mark.getValueAt(selectedRowIndex, 4).toString());
        String gender=Mark.getValueAt(selectedRowIndex,7).toString();      
    if(gender.equals("male")){
        male.setSelected(true);
    }    
    else{
        female.setSelected(true);
    }
        salary.setText(Mark.getValueAt(selectedRowIndex, 8).toString());
        
        String def=Mark.getValueAt(selectedRowIndex,9).toString();
       switch(def)
    {
        case "Company":
         department.setSelectedIndex(1);        
        break;
        case "Own Bussiness":
        department.setSelectedIndex(2);
        break;
        case "none":
        department.setSelectedIndex(3);
        break;
        case "n/a":
        department.setSelectedIndex(4);
        break;
        case "Office":
        department.setSelectedIndex(5);
        break;
       }
  
   String stat=Mark.getValueAt(selectedRowIndex,10).toString();
       switch(stat)
    {
        case "Single":
         status.setSelectedIndex(1);        
        break;
        case "Married":
        status.setSelectedIndex(2);
        break;
        case "In Relationship":
        status.setSelectedIndex(3);
        break;
        case "Devorce":
        status.setSelectedIndex(4);
        break;
        case "Widdow":
        status.setSelectedIndex(5);
        break;
       }
             String jo=Mark.getValueAt(selectedRowIndex,11).toString();
       switch(jo)
    {
        case "Other":
        job.setSelectedIndex(1);        
        break;
        case "Manager":
        job.setSelectedIndex(2);
        break;
        case "Employee":
        job.setSelectedIndex(3);
        break;
        case "Office":
        job.setSelectedIndex(4);
        break;
        case "Constraction":
        job.setSelectedIndex(5);
        break;
       }

    }//GEN-LAST:event_tabletaMouseClicked

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
 try{
            int i = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete this? ","Delete",JOptionPane.YES_NO_OPTION);
            if (i==0){
                String sql = "delete from TBL_USERS where EmpID=?";
                pst = con.prepareStatement(sql);
                pst.setString(1, id.getText());
                pst.execute();
              loadTable();
            rs.close();
            pst.close();      
            }else{
      
            }
            
        
        }catch(Exception e){
         JOptionPane.showMessageDialog(null, e);       
        }    }//GEN-LAST:event_delActionPerformed

    private void refActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refActionPerformed
    clear();        // TODO add your handling code here:
     
    }//GEN-LAST:event_refActionPerformed

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
      char mark =evt.getKeyChar();
      if( ! (Character.isDigit(mark) || (mark ==KeyEvent.VK_BACK_SPACE)))
      {
          evt.consume();
      }
    }//GEN-LAST:event_idKeyTyped

    private void fnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnKeyPressed

    private void fnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnKeyTyped

        
 char mark = evt.getKeyChar();
        
       if (Character.isLetter(mark) || Character.isWhitespace(mark) || Character.isUpperCase(mark))
       {
           fn.setEditable(true);
       }
       else {
           fn.setEditable(true);
       }        // TODO add your handling code here:
    }//GEN-LAST:event_fnKeyTyped

    private void lnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnKeyTyped

           char mark = evt.getKeyChar();  
       if (Character.isLetter(mark) || Character.isWhitespace(mark) || Character.isUpperCase(mark))
       {
           fn.setEditable(true);
       }
       else {
           fn.setEditable(true);
       }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_lnKeyTyped

    private void aKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aKeyTyped
      char mark =evt.getKeyChar();
      if( ! (Character.isDigit(mark) || (mark ==KeyEvent.VK_BACK_SPACE)))
      {
          evt.consume();
      }        // TODO add your handling code here:
    }//GEN-LAST:event_aKeyTyped

    private void HANAPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HANAPKeyReleased
DefaultTableModel Mark = (DefaultTableModel)tableta.getModel();
          String search_data = HANAP.getText().toLowerCase();
          TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(Mark);
          tableta.setRowSorter(tr);
          tr.setRowFilter(RowFilter.regexFilter(search_data));
// TODO add your handling code here:
    }//GEN-LAST:event_HANAPKeyReleased

    private void lnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnKeyReleased
int v1 = ln.getCaretPosition();
        ln.setText(ln.getText().toUpperCase());
        ln.setCaretPosition(v1);
            // TODO add your handling code here:
    }//GEN-LAST:event_lnKeyReleased

    private void fnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnKeyReleased
 int v1 = fn.getCaretPosition();
        fn.setText(fn.getText().toUpperCase());
        fn.setCaretPosition(v1);        // TODO add your handling code here:
    }//GEN-LAST:event_fnKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MANAGEEMPLOYEE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MANAGEEMPLOYEE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MANAGEEMPLOYEE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MANAGEEMPLOYEE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MANAGEEMPLOYEE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JTextField HANAP;
    private javax.swing.JTextField a;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton del;
    private javax.swing.JComboBox<String> department;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fn;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> job;
    private javax.swing.JTextField ln;
    private javax.swing.JRadioButton male;
    private javax.swing.JButton ref;
    private javax.swing.JTextField salary;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTable tableta;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
