/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee111819;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author icc.caloocan
 */
public class UPDATEALL extends javax.swing.JFrame {
 Connection con=null;
    PreparedStatement pst =null;
     ResultSet rs =null;
    String amountTotal;
    int salary_val;
    /**
     * Creates new form UPDATEALL
     */
    public UPDATEALL() {
        initComponents();
          con=Employee111819.connect();
         
    }
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ln = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hanap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        department = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        job = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        Amount = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        amt = new javax.swing.JRadioButton();
        p2 = new javax.swing.JRadioButton();
        Percentage = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        salary1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(ln);
        ln.setBounds(80, 480, 190, 40);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel6.setText("Employee Last Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 440, 160, 32);
        getContentPane().add(fn);
        fn.setBounds(80, 390, 190, 40);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel2.setText("Employee First Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 350, 160, 32);
        getContentPane().add(id);
        id.setBounds(80, 300, 190, 40);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel10.setText("Employee ID ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 260, 110, 32);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel3.setText("Employee ID ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 80, 110, 40);

        hanap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hanapActionPerformed(evt);
            }
        });
        hanap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hanapKeyReleased(evt);
            }
        });
        getContentPane().add(hanap);
        hanap.setBounds(220, 80, 350, 40);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Update Salary");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 550, 390, 60);

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel11.setText("Department");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(440, 260, 110, 32);
        getContentPane().add(department);
        department.setBounds(440, 300, 190, 40);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel5.setText("Job Title");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(440, 350, 160, 32);
        getContentPane().add(job);
        job.setBounds(440, 390, 190, 40);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel7.setText("Salary");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(440, 440, 160, 32);

        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });
        getContentPane().add(salary);
        salary.setBounds(440, 480, 190, 40);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Employee Iformation");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 150, 390, 60);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Update Salary");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(150, 550, 390, 60);

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel12.setText("Employee Last Name");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(80, 440, 160, 32);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(80, 480, 190, 40);
        getContentPane().add(Amount);
        Amount.setBounds(430, 660, 190, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 240, 620, 310);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(290, 110, 130, 40);

        jButton2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(140, 110, 130, 40);

        buttonGroup1.add(amt);
        amt.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        amt.setText("Amount");
        amt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amtActionPerformed(evt);
            }
        });
        jPanel2.add(amt);
        amt.setBounds(380, 10, 190, 40);

        buttonGroup1.add(p2);
        p2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        p2.setText("Percentage");
        p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });
        jPanel2.add(p2);
        p2.setBounds(30, 10, 200, 40);

        Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PercentageActionPerformed(evt);
            }
        });
        jPanel2.add(Percentage);
        Percentage.setBounds(30, 50, 200, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(49, 610, 620, 170);

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee111819/1.png"))); // NOI18N
        jButton6.setText("       BACK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(540, 790, 180, 60);

        salary1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salary1ActionPerformed(evt);
            }
        });
        getContentPane().add(salary1);
        salary1.setBounds(440, 480, 190, 40);

        setSize(new java.awt.Dimension(753, 901));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        MAIN obj = new MAIN();
        obj.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void hanapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hanapActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_hanapActionPerformed

    private void hanapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hanapKeyReleased
        try {
            String sql = "select * from TBL_USERS where EmpID=?";
            pst=con.prepareStatement(sql);
            pst.setString(1, hanap.getText());
            rs=pst.executeQuery();
            String val = rs.getString("EmpID");
            id.setText(val);
            String val2=rs.getString("FirstName");
            fn.setText(val2);
            String val3=rs.getString("LastName");
            ln.setText(val3);
            String val4=rs.getString("Department");
            department.setText(val4);
            String val5=rs.getString("JobTitle");
            job.setText(val5);
            String val6=rs.getString("Salary");
            salary.setText(val6);

        }catch(Exception e){
            
        }

        finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }









        // TODO add your handling code here:
    }//GEN-LAST:event_hanapKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        id.setText("");
        fn.setText("");
        ln.setText("");
        
        department.setText("");
        job.setText("");
        hanap.setText("");
        salary.setText("");
        Percentage.setEnabled(true);
        Amount.setEnabled(true); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

            try {
                      
                 int r =JOptionPane.showConfirmDialog(null, "Do you want to update salary?", "UPDATE SALARY", JOptionPane.YES_NO_OPTION);
        if(r == 0) {
          
           
            if(amt.isSelected() == true) {
             Percentage.setText("");
               Percentage.setEnabled(false);
                
                salary_val = Integer.parseInt(salary.getText());
                 int getAmount = Integer.parseInt(Amount.getText());
                int calcAmount = salary_val +  getAmount;
                amountTotal = String.valueOf(calcAmount);
               salary.setText(amountTotal);
              } 
                         else if(p2.isSelected() == true) {
              amt.setText("");
               amt.setEnabled(true);
                
                int getPercent = Integer.parseInt(Percentage.getText());
                int calcPercent = (salary_val) + (salary_val / 100 * getPercent);
                String perTotal = String.valueOf(calcPercent);
                salary.setText(perTotal);
                          }  
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
             try{
                  
               
                    String val1 = id.getText();
                 String val2 = salary.getText();
                 
                String sql = "update TBL_USERS set Salary='"+val2+"' where EmpID='"+val1+"'";
                pst = con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Record Updated");
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
            finally {
                try {
                    pst.close();
                    rs.close();
                   
                }
                catch(Exception e) {
            
                }
            }     
           
              // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
   Amount.setEnabled(false); 
        Percentage.setEnabled(true);
// TODO add your handling code here:
    }//GEN-LAST:event_p2ActionPerformed

    private void PercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PercentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PercentageActionPerformed

    private void amtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amtActionPerformed
        Percentage.setEnabled(false);
Amount.setEnabled(true); 
            // TODO add your handling code here:
    }//GEN-LAST:event_amtActionPerformed

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryActionPerformed

    private void salary1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salary1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salary1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UPDATEALL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UPDATEALL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UPDATEALL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UPDATEALL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPDATEALL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Amount;
    private javax.swing.JTextField Percentage;
    private javax.swing.JRadioButton amt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField department;
    private javax.swing.JTextField fn;
    private javax.swing.JTextField hanap;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField job;
    private javax.swing.JTextField ln;
    private javax.swing.JRadioButton p2;
    private javax.swing.JTextField salary;
    private javax.swing.JTextField salary1;
    // End of variables declaration//GEN-END:variables
}
