
import java.awt.Color;
import static java.awt.Color.red;
import java.awt.Font;
import java.awt.PageAttributes;
import static java.awt.PageAttributes.ColorType.COLOR;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author icc.caloocan
 */
public class ministore2 extends javax.swing.JFrame {

    /**
     * Creates new form ministore2
     */
    public ministore2() {
        initComponents();
        img1_off();
        img2_off();
         img3_off();
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void img1_off()
            
    {
        p1.setEnabled(false);
        q1.setEnabled(false);
        o1.setEnabled(false);
        c1.setEnabled(false);
        m.setEnabled(false);
        sukli.setEnabled(false);
        okay4.setEnabled(false);
        
    }
      public void img1_on()
    {
        q1.setEnabled(true);
        o1.setEnabled(true);
        c1.setEnabled(true);
        m.setEnabled(false);
        sukli.setEnabled(true);
        okay4.setEnabled(true);
    } 
         public void img2_off()
    {
        p2.setEnabled(false);
        q2.setEnabled(false);
        o2.setEnabled(false);
        c2.setEnabled(false);
    }
      public void img2_on()
    {
        q2.setEnabled(true);
        o2.setEnabled(true);
        c2.setEnabled(true);
    } 
      public void img3_off()
    {
        p3.setEnabled(false);
        q3.setEnabled(false);
        o3.setEnabled(false);
        c3.setEnabled(false);
    }
      public void img3_on()
    {
        q3.setEnabled(true);
        o3.setEnabled(true);
        c3.setEnabled(true);
    } 
            
            
            
            
    int val1,val2,val3,total,money;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        c1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        q1 = new javax.swing.JTextField();
        o1 = new javax.swing.JButton();
        o2 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        q2 = new javax.swing.JTextField();
        o3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        okay4 = new javax.swing.JButton();
        m = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        transasc = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sukli = new javax.swing.JTextField();
        c3 = new javax.swing.JButton();
        q3 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        p1 = new javax.swing.JTextField();
        t = new javax.swing.JButton();
        display = new javax.swing.JTextField();
        p2 = new javax.swing.JTextField();
        p3 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Transaction Details");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Money:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Change:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Okay");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Next Transaction");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 255));
        jLabel4.setText("     Hi I'm Mark Louis");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 140, 380, 330);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(430, 30, 410, 520);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 70, 0, 0);

        img1.setBackground(new java.awt.Color(204, 204, 204));
        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/m.JPG"))); // NOI18N
        img1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img1MouseClicked(evt);
            }
        });
        getContentPane().add(img1);
        img1.setBounds(470, 50, 193, 155);

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Sushimo");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(680, 50, 102, 21);

        jLabel19.setBackground(new java.awt.Color(204, 204, 204));
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Price");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(680, 510, 48, 22);

        img2.setBackground(new java.awt.Color(204, 204, 204));
        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a.JPG"))); // NOI18N
        img2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img2MouseClicked(evt);
            }
        });
        getContentPane().add(img2);
        img2.setBounds(480, 250, 197, 173);

        img3.setBackground(new java.awt.Color(204, 204, 204));
        img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r.JPG"))); // NOI18N
        img3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img3MouseClicked(evt);
            }
        });
        getContentPane().add(img3);
        img3.setBounds(480, 470, 197, 180);

        jLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Ramen");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(680, 470, 92, 29);

        jLabel20.setBackground(new java.awt.Color(204, 204, 204));
        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Price");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(690, 300, 50, 22);

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Takoyakiko");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(690, 250, 140, 28);

        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Quanlity");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(680, 560, 70, 22);

        c1.setBackground(new java.awt.Color(204, 204, 204));
        c1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c1.setForeground(new java.awt.Color(204, 0, 0));
        c1.setText("Cancel");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(830, 180, 110, 30);

        jLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Price");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(690, 90, 48, 22);

        jLabel21.setBackground(new java.awt.Color(204, 204, 204));
        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Quanlity");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(680, 140, 70, 22);

        q1.setBackground(new java.awt.Color(204, 204, 204));
        q1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1ActionPerformed(evt);
            }
        });
        getContentPane().add(q1);
        q1.setBounds(760, 130, 170, 37);

        o1.setBackground(new java.awt.Color(204, 204, 204));
        o1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        o1.setText("Okay");
        o1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o1ActionPerformed(evt);
            }
        });
        getContentPane().add(o1);
        o1.setBounds(700, 180, 103, 30);

        o2.setBackground(new java.awt.Color(204, 204, 204));
        o2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        o2.setText("Okay");
        o2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o2ActionPerformed(evt);
            }
        });
        getContentPane().add(o2);
        o2.setBounds(700, 400, 100, 30);

        c2.setBackground(new java.awt.Color(204, 204, 204));
        c2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c2.setForeground(new java.awt.Color(204, 0, 0));
        c2.setText("Cancel");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2);
        c2.setBounds(830, 400, 110, 30);

        jLabel23.setBackground(new java.awt.Color(204, 204, 204));
        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Quanlity");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(680, 350, 70, 22);

        q2.setBackground(new java.awt.Color(204, 204, 204));
        q2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2ActionPerformed(evt);
            }
        });
        getContentPane().add(q2);
        q2.setBounds(760, 340, 170, 40);

        o3.setBackground(new java.awt.Color(204, 204, 204));
        o3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        o3.setText("Okay");
        o3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o3ActionPerformed(evt);
            }
        });
        getContentPane().add(o3);
        o3.setBounds(700, 620, 100, 30);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(null);

        okay4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        okay4.setText("Okay");
        okay4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        okay4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okay4ActionPerformed(evt);
            }
        });
        jPanel5.add(okay4);
        okay4.setBounds(141, 150, 200, 21);

        m.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });
        jPanel5.add(m);
        m.setBounds(140, 70, 200, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Transaction Details");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(41, 0, 318, 50);

        transasc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        transasc.setText("Next Transaction");
        transasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transascActionPerformed(evt);
            }
        });
        jPanel5.add(transasc);
        transasc.setBounds(141, 190, 200, 25);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("     Hi I'm Mark");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(141, 230, 202, 90);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Change");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(41, 110, 100, 42);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Money");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(41, 60, 90, 37);

        sukli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sukli.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        sukli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sukliActionPerformed(evt);
            }
        });
        jPanel5.add(sukli);
        sukli.setBounds(140, 110, 200, 30);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(40, 220, 400, 310);

        c3.setBackground(new java.awt.Color(204, 204, 204));
        c3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c3.setForeground(new java.awt.Color(204, 0, 0));
        c3.setText("Cancel");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        getContentPane().add(c3);
        c3.setBounds(820, 620, 110, 30);

        q3.setBackground(new java.awt.Color(204, 204, 204));
        q3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3ActionPerformed(evt);
            }
        });
        getContentPane().add(q3);
        q3.setBounds(760, 550, 170, 40);

        jLabel25.setBackground(new java.awt.Color(153, 153, 153));
        jLabel25.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("     Mark Mini Store");
        jLabel25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel25.setOpaque(true);
        getContentPane().add(jLabel25);
        jLabel25.setBounds(40, 630, 380, 50);

        p1.setBackground(new java.awt.Color(204, 204, 204));
        p1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        p1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p1.setText("100");
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        getContentPane().add(p1);
        p1.setBounds(760, 80, 170, 40);

        t.setBackground(new java.awt.Color(204, 204, 204));
        t.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t.setText("Total");
        t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tActionPerformed(evt);
            }
        });
        getContentPane().add(t);
        t.setBounds(580, 690, 110, 40);

        display.setBackground(new java.awt.Color(204, 204, 204));
        display.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        getContentPane().add(display);
        display.setBounds(700, 690, 180, 40);

        p2.setBackground(new java.awt.Color(204, 204, 204));
        p2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        p2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p2.setText("45");
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });
        getContentPane().add(p2);
        p2.setBounds(760, 290, 170, 40);

        p3.setBackground(new java.awt.Color(204, 204, 204));
        p3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        p3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p3.setText("65");
        p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3ActionPerformed(evt);
            }
        });
        getContentPane().add(p3);
        p3.setBounds(760, 500, 170, 40);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(450, 30, 520, 710);

        setSize(new java.awt.Dimension(997, 817));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
        // TODO add your handling code here:
        m.getText();
        
    }//GEN-LAST:event_mActionPerformed

    private void transascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transascActionPerformed
        q1.setText("");
        q2.setText("");
        q3.setText(""); 
        display.setText("");
        sukli.setText("");
        m.setText("");  
        img1_off();
        img2_off();
        img3_off();
    }//GEN-LAST:event_transascActionPerformed

    private void o2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o2ActionPerformed
          q2.setForeground(Color.green);
        q2.setFont(new Font("Arial", Font.PLAIN,30));
        q2.setHorizontalAlignment(q2.CENTER);
        val2=Integer.parseInt(p2.getText( )) * Integer.parseInt(q2.getText( ));
    }//GEN-LAST:event_o2ActionPerformed

    private void q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1ActionPerformed
        // TODO add your handling code here:
      q1.getText();
      
  
    }//GEN-LAST:event_q1ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
        total=total-val3;
        display.setText(String.valueOf(total));
    }//GEN-LAST:event_c3ActionPerformed

    private void sukliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sukliActionPerformed
       
    }//GEN-LAST:event_sukliActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed


    p1.getText();       // TODO add your handling code here:
    }//GEN-LAST:event_p1ActionPerformed

    private void o1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o1ActionPerformed
        // TODO add your handling code here:
        q1.setForeground(Color.green);
        q1.setFont(new Font("Arial", Font.PLAIN,30));
        q1.setHorizontalAlignment(q1.CENTER);
        val1=Integer.parseInt(p1.getText( )) * Integer.parseInt(q1.getText( ));
 

    }//GEN-LAST:event_o1ActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    private void tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tActionPerformed
        total=val1+val2+val3;
        if(total>0)
        {
        
        display.setText(String.valueOf(total));
        display.setText(String.valueOf(total));
        display.setEnabled(false);
        display.setFont(new Font("Arial", Font.BOLD,30));
        display.setHorizontalAlignment(display.CENTER);
        }
        else{
            
        }
    }//GEN-LAST:event_tActionPerformed

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        p2.getText();
    }//GEN-LAST:event_p2ActionPerformed

    private void q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2ActionPerformed
        // TODO add your handling code here:
        q2.getText();
    }//GEN-LAST:event_q2ActionPerformed

    private void o3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o3ActionPerformed
        q3.setForeground(Color.green);
        q3.setFont(new Font("Arial", Font.PLAIN,30));
        q3.setHorizontalAlignment(q3.CENTER);
        val3=Integer.parseInt(p3.getText( )) * Integer.parseInt(q3.getText( ));
    }//GEN-LAST:event_o3ActionPerformed

    private void p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3ActionPerformed
        // TODO add your handling code here:
        p3.getText();
    }//GEN-LAST:event_p3ActionPerformed

    private void q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3ActionPerformed
       q3.getText();
    }//GEN-LAST:event_q3ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        q1.setText(" ");
        total=total-val1;
        display.setText(String.valueOf(total));
        
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
          q2.setText(" ");
          total=total-val2;
        display.setText(String.valueOf(total));
    }//GEN-LAST:event_c2ActionPerformed

    private void okay4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okay4ActionPerformed
        money=Integer.parseInt(m.getText( ))- total;
        
        
        if (money<=0)
        {
            JOptionPane.showMessageDialog(null,"Insufficient Balance");
        }
        else{
            sukli.setText(String.valueOf(money)); 
        }
      
    }//GEN-LAST:event_okay4ActionPerformed

    private void img1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img1MouseClicked
        q1.setEnabled(true);
        o1.setEnabled(true);
        c1.setEnabled(true);  
        m.setEnabled(true);
        sukli.setEnabled(true);
        okay4.setEnabled(true);// TODO add your handling code here:

    }//GEN-LAST:event_img1MouseClicked

    private void img2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img2MouseClicked
        // TODO add your handling code here:
        q2.setEnabled(true);
        o2.setEnabled(true);
        c2.setEnabled(true);
   
      
    }//GEN-LAST:event_img2MouseClicked

    private void img3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img3MouseClicked
        // TODO add your handling code here:
        q3.setEnabled(true);
        o3.setEnabled(true);
        c3.setEnabled(true);
    }//GEN-LAST:event_img3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ministore2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ministore2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ministore2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ministore2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ministore2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c1;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JTextField display;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField m;
    private javax.swing.JButton o1;
    private javax.swing.JButton o2;
    private javax.swing.JButton o3;
    private javax.swing.JButton okay4;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField p3;
    private javax.swing.JTextField q1;
    private javax.swing.JTextField q2;
    private javax.swing.JTextField q3;
    private javax.swing.JTextField sukli;
    private javax.swing.JButton t;
    private javax.swing.JButton transasc;
    // End of variables declaration//GEN-END:variables
}
