
import java.awt.Font;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author icc.caloocan
 */
public class store extends javax.swing.JFrame {

    /**
     * Creates new form store
     */
    public store() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
int val1,val2,val3,total;
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t = new javax.swing.JButton();
        display = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        price = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture2.JPG"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(620, 130, 250, 210);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture3.JPG"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 130, 250, 210);

        t.setText("Compute");
        t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tActionPerformed(evt);
            }
        });
        getContentPane().add(t);
        t.setBounds(40, 470, 140, 50);

        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        getContentPane().add(display);
        display.setBounds(200, 470, 390, 50);

        clear.setText("Reset");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(610, 470, 130, 50);

        price.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        price.setText("Price");
        getContentPane().add(price);
        price.setBounds(10, 400, 100, 40);

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("                                 Mark Mini Store");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 880, 70);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Products");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 90, 210, 40);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setText("P");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(670, 400, 40, 40);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setText("P");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(120, 400, 40, 40);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setText("P");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(390, 400, 40, 40);

        cb1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cb1.setForeground(new java.awt.Color(0, 204, 204));
        cb1.setText("Sushimo");
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1);
        cb1.setBounds(120, 360, 77, 23);

        cb2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cb2.setForeground(new java.awt.Color(0, 204, 204));
        cb2.setText("Takoyakiko");
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });
        getContentPane().add(cb2);
        cb2.setBounds(410, 360, 100, 23);

        cb3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cb3.setForeground(new java.awt.Color(0, 204, 204));
        cb3.setText("Ramen");
        cb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3ActionPerformed(evt);
            }
        });
        getContentPane().add(cb3);
        cb3.setBounds(670, 360, 67, 23);

        p1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        p1.setText("25");
        getContentPane().add(p1);
        p1.setBounds(150, 400, 80, 40);

        p2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        p2.setText("30");
        getContentPane().add(p2);
        p2.setBounds(420, 400, 60, 40);

        p3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        p3.setText("35");
        getContentPane().add(p3);
        p3.setBounds(700, 400, 60, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mark/asd.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 130, 220, 210);

        setBounds(0, 0, 919, 637);
    }// </editor-fold>//GEN-END:initComponents

    private void tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tActionPerformed
        // TODO add your handling code here:
         total=val1+val2+val3;   
         display.setText(String.valueOf(total));
                  display.setFont(new Font("Arial", Font.BOLD,30));
                  
         display.setHorizontalAlignment(display.CENTER);

    }//GEN-LAST:event_tActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
       
         cb1.setSelected(false);
         cb2.setSelected(false);
         cb3.setSelected(false);
         
         
         p1.setForeground(java.awt.Color.black);
              p2.setForeground(java.awt.Color.black);
                   p3.setForeground(java.awt.Color.black);
                   
        display.setText("");
       
    }//GEN-LAST:event_clearActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
             if(cb1.isSelected())
        {
            val1=Integer.parseInt(p1.getText( ));
            p1.setForeground(java.awt.Color.green);

        }
        else
        {
            val2=0;
            p1.setForeground(java.awt.Color.black);
        }
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
   if(cb2.isSelected())
        {
            val2=Integer.parseInt(p2.getText( ));
            p2.setForeground(java.awt.Color.green);

        }
        else
        {
            val2=0;
            p2.setForeground(java.awt.Color.black);
        }
                         
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3ActionPerformed
        // TODO add your handling code here:
           if(cb3.isSelected())
        {
            val3=Integer.parseInt(p3.getText( ));
            p3.setForeground(java.awt.Color.green);

        }
        else
        {
            val3=0;
            p3.setForeground(java.awt.Color.black);
        
    }                     
    }//GEN-LAST:event_cb3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new store().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JButton clear;
    private javax.swing.JTextField display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel price;
    private javax.swing.JButton t;
    // End of variables declaration//GEN-END:variables

    private String String(int total) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
