
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author icc.caloocan
 */
public class calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    public calculator() {
        initComponents();
        on1_off();
        off1_off();
       
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
        double num,ans;
        int opt;
 
      public void on1_on() {
        b0.setEnabled(true);
        b1.setEnabled(true);
        b2.setEnabled(true);
        b3.setEnabled(true);
        b4.setEnabled(true);
        b5.setEnabled(true);
        b6.setEnabled(true);
        b7.setEnabled(true);
        b8.setEnabled(true);
        b9.setEnabled(true);
        c.setEnabled(true);
        del.setEnabled(true);
        m.setEnabled(true);
        m1.setEnabled(true);
        m2.setEnabled(true);
        m4.setEnabled(true);
        d1.setEnabled(true);
        equal.setEnabled(true);
        on1.setEnabled(false);
        


    }
    public void on1_off() {
        b0.setEnabled(false);
        b1.setEnabled(false);
        b2.setEnabled(false);
        b3.setEnabled(false);
        b4.setEnabled(false);
        b5.setEnabled(false);
        b6.setEnabled(false);
        b7.setEnabled(false);
        b8.setEnabled(false);
        b9.setEnabled(false);
        c.setEnabled(false);
        del.setEnabled(false);
        m.setEnabled(false);
        m1.setEnabled(false);
        m2.setEnabled(false);
        m4.setEnabled(false);
        equal.setEnabled(false);
        d1.setEnabled(false);

    }

  

    public void off1_off() {
        b0.setEnabled(false);
        b1.setEnabled(false);
        b2.setEnabled(false);
        b3.setEnabled(false);
        b4.setEnabled(false);
        b5.setEnabled(false);
        b6.setEnabled(false);
        b7.setEnabled(false);
        b8.setEnabled(false);
        b9.setEnabled(false);
        c.setEnabled(false);
        del.setEnabled(false);
        m.setEnabled(false);
        m1.setEnabled(false);
        m2.setEnabled(false);
        m4.setEnabled(false);
        d1.setEnabled(false);

    }

    public void off1_on() {
        b0.setEnabled(true);
        b1.setEnabled(true);
        b2.setEnabled(true);
        b3.setEnabled(true);
        b4.setEnabled(true);
        b5.setEnabled(true);
        b6.setEnabled(true);
        b7.setEnabled(true);
        b8.setEnabled(true);
        b9.setEnabled(true);
        c.setEnabled(true);
        del.setEnabled(true);
        m.setEnabled(true);
        m1.setEnabled(true);
        m2.setEnabled(true);
        m4.setEnabled(true);
        equal.setEnabled(true);


    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        display = new javax.swing.JTextField();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        d1 = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        m4 = new javax.swing.JButton();
        m = new javax.swing.JButton();
        m1 = new javax.swing.JButton();
        m2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        off1 = new javax.swing.JRadioButton();
        on1 = new javax.swing.JRadioButton();
        c = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        del = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        display.setBackground(new java.awt.Color(204, 204, 204));
        display.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        display.setBorder(new javax.swing.border.MatteBorder(null));
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        getContentPane().add(display);
        display.setBounds(20, 10, 500, 81);

        b8.setBackground(new java.awt.Color(204, 255, 255));
        b8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b8.setText("8");
        b8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8);
        b8.setBounds(160, 290, 130, 57);

        b9.setBackground(new java.awt.Color(204, 255, 255));
        b9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b9.setText("9");
        b9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9);
        b9.setBounds(300, 290, 130, 57);

        b5.setBackground(new java.awt.Color(204, 255, 255));
        b5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b5.setText("5");
        b5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5);
        b5.setBounds(160, 370, 130, 57);

        b6.setBackground(new java.awt.Color(204, 255, 255));
        b6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b6.setText("6");
        b6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6);
        b6.setBounds(300, 370, 130, 57);

        b4.setBackground(new java.awt.Color(204, 255, 255));
        b4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b4.setText("4");
        b4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4);
        b4.setBounds(20, 370, 130, 57);

        b2.setBackground(new java.awt.Color(204, 255, 255));
        b2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b2.setText("2");
        b2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(160, 450, 130, 57);

        b3.setBackground(new java.awt.Color(204, 255, 255));
        b3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b3.setText("3");
        b3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(300, 450, 130, 57);

        b1.setBackground(new java.awt.Color(204, 255, 255));
        b1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b1.setText("1");
        b1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(20, 450, 130, 57);

        d1.setBackground(new java.awt.Color(204, 255, 255));
        d1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        d1.setText(".");
        d1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });
        getContentPane().add(d1);
        d1.setBounds(160, 530, 130, 57);

        equal.setBackground(new java.awt.Color(51, 51, 51));
        equal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        equal.setText("=");
        equal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });
        getContentPane().add(equal);
        equal.setBounds(300, 527, 130, 60);

        b0.setBackground(new java.awt.Color(204, 255, 255));
        b0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b0.setText("0");
        b0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        getContentPane().add(b0);
        b0.setBounds(20, 530, 130, 57);

        m4.setBackground(new java.awt.Color(204, 255, 255));
        m4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        m4.setText("+");
        m4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        m4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m4ActionPerformed(evt);
            }
        });
        getContentPane().add(m4);
        m4.setBounds(440, 440, 80, 150);

        m.setBackground(new java.awt.Color(204, 255, 255));
        m.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        m.setText("*");
        m.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });
        getContentPane().add(m);
        m.setBounds(440, 170, 80, 70);

        m1.setBackground(new java.awt.Color(204, 255, 255));
        m1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        m1.setText("-");
        m1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });
        getContentPane().add(m1);
        m1.setBounds(440, 250, 80, 80);

        m2.setBackground(new java.awt.Color(204, 255, 255));
        m2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        m2.setText("/");
        m2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2ActionPerformed(evt);
            }
        });
        getContentPane().add(m2);
        m2.setBounds(440, 340, 80, 90);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Markme");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 100, 200, 40);

        off1.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup2.add(off1);
        off1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        off1.setText("OFF");
        off1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        off1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                off1ActionPerformed(evt);
            }
        });
        jPanel1.add(off1);
        off1.setBounds(380, 100, 120, 40);

        on1.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup2.add(on1);
        on1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        on1.setText("ON");
        on1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        on1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on1ActionPerformed(evt);
            }
        });
        jPanel1.add(on1);
        on1.setBounds(20, 100, 120, 40);

        c.setBackground(new java.awt.Color(153, 153, 153));
        c.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c.setForeground(new java.awt.Color(255, 255, 255));
        c.setText("C");
        c.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        jPanel1.add(c);
        c.setBounds(50, 200, 170, 70);

        b7.setBackground(new java.awt.Color(204, 255, 255));
        b7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b7.setText("7");
        b7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel1.add(b7);
        b7.setBounds(20, 290, 130, 57);

        del.setBackground(new java.awt.Color(153, 0, 0));
        del.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        del.setForeground(new java.awt.Color(255, 255, 255));
        del.setText("DEL");
        del.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        jPanel1.add(del);
        del.setBounds(250, 200, 170, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 540, 400);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(440, 170, 90, 80);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 400, 250, 240);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(250, 400, 290, 240);

        setBounds(0, 0, 559, 675);
    }// </editor-fold>//GEN-END:initComponents

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        display.setText(display.getText()+"6");     
    }//GEN-LAST:event_b6ActionPerformed

    private void on1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on1ActionPerformed

        b0.setEnabled(true);
        b1.setEnabled(true);
        b2.setEnabled(true);
        b3.setEnabled(true);
        b4.setEnabled(true);
        b5.setEnabled(true);
        b6.setEnabled(true);
        b7.setEnabled(true);
        b8.setEnabled(true);
        b9.setEnabled(true);
        c.setEnabled(true);
        del.setEnabled(true);
        m.setEnabled(true);
        m1.setEnabled(true);
        m2.setEnabled(true);
        m4.setEnabled(true);
        equal.setEnabled(true);
        d1.setEnabled(true);
  
    }//GEN-LAST:event_on1ActionPerformed

    private void off1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_off1ActionPerformed
        // TODO add your handling code here:
        display.setText("");
        b0.setEnabled(false);
        b1.setEnabled(false);
        b2.setEnabled(false);
        b3.setEnabled(false);
        b4.setEnabled(false);
        b5.setEnabled(false);
        b6.setEnabled(false);
        b7.setEnabled(false);
        b8.setEnabled(false);
        b9.setEnabled(false);
        c.setEnabled(false);
        del.setEnabled(false);
        m.setEnabled(false);
        m1.setEnabled(false);
        m2.setEnabled(false);
        m4.setEnabled(false);
        equal.setEnabled(false);
        d1.setEnabled(true);
     


    }//GEN-LAST:event_off1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
   display.setText(display.getText()+"1");       
    }//GEN-LAST:event_b1ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        display.setText(display.getText()+"0");     

        // TODO add your handling code here:
    }//GEN-LAST:event_b0ActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        

        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
display.setText(display.getText()+"2");             // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
       display.setText(display.getText()+"3");     
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
display.setText(display.getText()+"5");          // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
display.setText(display.getText()+"4");          // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
display.setText(display.getText()+"7");          // TODO add your handling code here:
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
display.setText(display.getText()+"8");          // TODO add your handling code here:
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
display.setText(display.getText()+"9");          // TODO add your handling code here:
    }//GEN-LAST:event_b9ActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
 int var=display.getText().length();
        String dis;
        int var1=display.getText().length()-1;
        
        if(var>0)
        {
            StringBuilder backspace=new StringBuilder(display.getText());
            backspace.deleteCharAt(var1);
            dis=backspace.toString();
            display.setText(dis);
        }                // TODO add your handling code here:
    }//GEN-LAST:event_delActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
    display.setText("");           // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void m4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m4ActionPerformed
    
    num=Double.parseDouble(display.getText());     
    display.setText("");
    opt=1;// TODO add your handling code here:
    }//GEN-LAST:event_m4ActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
           switch(opt)
            {
                case 1:
                ans=num+Double.parseDouble(display.getText());
                display.setText(Double.toString(ans));
                break;

                case 2:
                ans=num-Double.parseDouble(display.getText());
                display.setText(Double.toString(ans));
                break;
                
                case 3:
                ans=num/Double.parseDouble(display.getText());
                display.setText(Double.toString(ans));
                break;
                  case 4:
                ans=num*Double.parseDouble(display.getText());
                display.setText(Double.toString(ans));
                break;
           }
           



        // TODO add your handling code here:
    }//GEN-LAST:event_equalActionPerformed

    private void m2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2ActionPerformed
 num=Double.parseDouble(display.getText());     
    display.setText("");
    opt=3;        // TODO add your handling code here:
    }//GEN-LAST:event_m2ActionPerformed

    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
num=Double.parseDouble(display.getText());     
    display.setText("");
    opt=2;        // TODO add your handling code here:
    }//GEN-LAST:event_m1ActionPerformed

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
num=Double.parseDouble(display.getText());     
    display.setText("");
    opt=4;        // TODO add your handling code here:
    }//GEN-LAST:event_mActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton c;
    private javax.swing.JButton d1;
    private javax.swing.JButton del;
    private javax.swing.JTextField display;
    private javax.swing.JButton equal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton m;
    private javax.swing.JButton m1;
    private javax.swing.JButton m2;
    private javax.swing.JButton m4;
    private javax.swing.JRadioButton off1;
    private javax.swing.JRadioButton on1;
    // End of variables declaration//GEN-END:variables
}
