/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframeinfo;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ComponentListener;

/**
 *
 * @author icc.caloocan
 */
public class jframeinformation extends javax.swing.JFrame {

    /**
     * Creates new form jframeinformation
     */
    public jframeinformation() {
        initComponents();
    del.setForeground(java.awt.Color.red);
    del.setBackground(java.awt.Color.black);
    del.setFont(new Font("Vladimir Script", Font.BOLD,18));
    display.setForeground(java.awt.Color.red);
    display.setBackground(java.awt.Color.black);
    display.setFont(new Font("Vladimir Script", Font.BOLD,18));
    name.setBackground(Color.black);
    name.setForeground(java.awt.Color.white);
    gitna.setBackground(Color.black);
    gitna.setForeground(java.awt.Color.white);
    apelido.setBackground(Color.black);
    apelido.setForeground(java.awt.Color.white);
    taon.setBackground(Color.black);
    taon.setForeground(java.awt.Color.white);
    output.setBackground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        fn = new javax.swing.JLabel();
        ln = new javax.swing.JLabel();
        mi = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        gitna = new javax.swing.JTextField();
        apelido = new javax.swing.JTextField();
        taon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        display = new javax.swing.JButton();
        output = new javax.swing.JLabel();
        del = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                none(evt);
            }
        });
        getContentPane().setLayout(null);

        fn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fn.setText("First name");
        getContentPane().add(fn);
        fn.setBounds(10, 100, 159, 38);

        ln.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ln.setText("Last name");
        getContentPane().add(ln);
        ln.setBounds(10, 230, 159, 38);

        mi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mi.setText("Middle Initial");
        getContentPane().add(mi);
        mi.setBounds(10, 170, 159, 38);

        age.setText("Age");
        getContentPane().add(age);
        age.setBounds(10, 300, 159, 38);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(190, 100, 220, 40);
        getContentPane().add(gitna);
        gitna.setBounds(190, 170, 220, 38);

        apelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apelidoActionPerformed(evt);
            }
        });
        getContentPane().add(apelido);
        apelido.setBounds(190, 230, 220, 40);
        getContentPane().add(taon);
        taon.setBounds(190, 300, 220, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jframeinfo/folder/jkjkj_1.jpg"))); // NOI18N
        jLabel5.setText("                   Image");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(430, 70, 160, 150);

        display.setText("Display");
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        getContentPane().add(display);
        display.setBounds(30, 420, 118, 57);
        getContentPane().add(output);
        output.setBounds(20, 500, 540, 75);

        del.setBackground(new java.awt.Color(255, 255, 255));
        del.setText("Clear");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        getContentPane().add(del);
        del.setBounds(410, 420, 170, 60);

        setSize(new java.awt.Dimension(644, 773));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed

    }//GEN-LAST:event_nameActionPerformed

    private void apelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apelidoActionPerformed

    }//GEN-LAST:event_apelidoActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
       output.setText("your name is"+ " " +name.getText()+" "+gitna.getText()+ " "+apelido.getText()+" " +"your age is "+taon.getText());
    }//GEN-LAST:event_displayActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
    del.setForeground(java.awt.Color.red);
    del.setBackground(java.awt.Color.black);
    del.setFont(new Font("Vladimir Script", Font.BOLD,18)); 
     output.setText("");
     name.setText(" ");
     gitna.setText(" ");
     apelido.setText(" ");
     taon.setText(" ");
    }//GEN-LAST:event_delActionPerformed

    private void none(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframeinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframeinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframeinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframeinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframeinformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JTextField apelido;
    private javax.swing.JButton del;
    private javax.swing.JButton display;
    private javax.swing.JLabel fn;
    private javax.swing.JTextField gitna;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel ln;
    private javax.swing.JLabel mi;
    private javax.swing.JTextField name;
    private javax.swing.JLabel output;
    private javax.swing.JTextField taon;
    // End of variables declaration//GEN-END:variables
}
