/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginform;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author icc.caloocan
 */
public class Main_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Main_Frame
     */
    public Main_Frame() {
        initComponents();
        trash();
      
    }

    public void trash(){
           box1.setText("");
           box2.setText("");
           box3.setText("");
           box4.setText("");   
           box5.setText("");            
    }

    public void Wtite()
    {
         String path = "‪C:\\Users\\icc.caloocan\\Desktop\\meme.txt";
         File records= new File(path);
    
    try
        
    {
        FileWriter fw = new FileWriter (records);
        BufferedWriter bw=new BufferedWriter(fw);
        
        for(int r=0;r<box.getRowCount();r++)
        {
            for(int c=0;c<box.getColumnCount();c++)
            {
                bw.write(box.getValueAt(r,c).toString()+ " ");
            }
            bw.newLine();
        }        
        bw.close();
        fw.close();
        JOptionPane.showMessageDialog(null,"Record Saved !");
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null,e);
    }
    }
    
    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        box = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        box1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        box2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        box5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ISBN = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        box3 = new javax.swing.JTextField();
        box4 = new javax.swing.JTextField();
        ADD = new javax.swing.JButton();
        CLEAR = new javax.swing.JButton();
        SAVE = new javax.swing.JButton();
        UPDATE = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        box.setBackground(new java.awt.Color(51, 51, 51));
        box.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book Name", "Book Category", "Author", "ISBN"
            }
        ));
        box.setRowHeight(35);
        jScrollPane1.setViewportView(box);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 70, 820, 480);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel3.setText("Book ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 50, 162, 42);

        box1.setBackground(new java.awt.Color(153, 153, 153));
        box1.setForeground(new java.awt.Color(255, 255, 255));
        box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1ActionPerformed(evt);
            }
        });
        getContentPane().add(box1);
        box1.setBounds(30, 100, 250, 50);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel4.setText("Book Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 160, 162, 42);

        box2.setBackground(new java.awt.Color(153, 153, 153));
        box2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(box2);
        box2.setBounds(30, 200, 250, 50);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel5.setText("Book Category");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 260, 200, 42);

        box5.setBackground(new java.awt.Color(153, 153, 153));
        box5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(box5);
        box5.setBounds(30, 500, 250, 50);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel6.setText("Author");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 360, 200, 42);

        ISBN.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        ISBN.setText("ISBN");
        getContentPane().add(ISBN);
        ISBN.setBounds(40, 460, 200, 42);

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 2, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Markme");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 660, 640, 70);

        box3.setBackground(new java.awt.Color(153, 153, 153));
        box3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(box3);
        box3.setBounds(30, 300, 250, 50);

        box4.setBackground(new java.awt.Color(153, 153, 153));
        box4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(box4);
        box4.setBounds(30, 400, 250, 50);

        ADD.setBackground(new java.awt.Color(102, 102, 102));
        ADD.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        ADD.setText("ADD");
        ADD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        getContentPane().add(ADD);
        ADD.setBounds(30, 590, 210, 50);

        CLEAR.setBackground(new java.awt.Color(102, 102, 102));
        CLEAR.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        CLEAR.setText("CLEAR");
        CLEAR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(CLEAR);
        CLEAR.setBounds(920, 590, 200, 50);

        SAVE.setBackground(new java.awt.Color(102, 102, 102));
        SAVE.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        SAVE.setText("SAVE");
        SAVE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });
        getContentPane().add(SAVE);
        SAVE.setBounds(260, 590, 200, 50);

        UPDATE.setBackground(new java.awt.Color(102, 102, 102));
        UPDATE.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        UPDATE.setText("UPDATE");
        UPDATE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });
        getContentPane().add(UPDATE);
        UPDATE.setBounds(480, 590, 200, 50);

        DELETE.setBackground(new java.awt.Color(102, 102, 102));
        DELETE.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        DELETE.setText("DELETE");
        DELETE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(DELETE);
        DELETE.setBounds(700, 590, 200, 50);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1170, 750);

        setSize(new java.awt.Dimension(1186, 789));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        DefaultTableModel Mark = (DefaultTableModel)box.getModel();
        
        Mark.addRow(new Object[] 
        {      
           box1.getText(),
           box2.getText(),
           box3.getText(),
           box4.getText(),   
           box5.getText(),               
        }       
                );    


    trash();





        // TODO add your handling code here:
    }//GEN-LAST:event_ADDActionPerformed

    private void box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box1ActionPerformed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
       
    
Wtite();
        // TODO add your handling code here:
    }//GEN-LAST:event_SAVEActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
  DefaultTableModel Mark = (DefaultTableModel)box.getModel();
  int i=  box.getSelectedRow();
  
  if(i>=0)
  {
      box.setValueAt(box1, i, 0);
      box.setValueAt(box1, i, 1);
      box.setValueAt(box1, i, 2);
      box.setValueAt(box1, i, 3);
      box.setValueAt(box1, i, 4);
  
      JOptionPane.showMessageDialog(null,"Successfully Updated!");
  
  }

        // TODO add your handling code here:
    }//GEN-LAST:event_UPDATEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JButton CLEAR;
    private javax.swing.JButton DELETE;
    private javax.swing.JLabel ISBN;
    private javax.swing.JButton SAVE;
    private javax.swing.JButton UPDATE;
    private javax.swing.JTable box;
    private javax.swing.JTextField box1;
    private javax.swing.JTextField box2;
    private javax.swing.JTextField box3;
    private javax.swing.JTextField box4;
    private javax.swing.JTextField box5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
